name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: |
        dotnet restore EasyLauncher/EasyLauncher.csproj
        dotnet restore Components/CastleStoryLauncher/CastleStoryLauncher.csproj
        dotnet restore Components/LANServer/LANServer.csproj
        dotnet restore Components/LANClient/LANClient.csproj
        dotnet restore Components/MultiplayerServer/MultiplayerServer.csproj
        dotnet restore Components/Mods/MultiplayerMod/MultiplayerMod.csproj
    
    - name: Build Easy Launcher
      run: |
        cd EasyLauncher
        dotnet build -c Release -r win-x64 --self-contained false
    
    - name: Build Castle Story Launcher
      run: |
        cd Components/CastleStoryLauncher
        dotnet build -c Release -r win-x64 --self-contained false
    
    - name: Build LAN Server
      run: |
        cd Components/LANServer
        dotnet build -c Release -r win-x64 --self-contained false
    
    - name: Build LAN Client
      run: |
        cd Components/LANClient
        dotnet build -c Release -r win-x64 --self-contained false
    
    - name: Build Multiplayer Server
      run: |
        cd Components/MultiplayerServer
        dotnet build -c Release -r win-x64 --self-contained false
    
    - name: Build Multiplayer Mod
      run: |
        cd Components/Mods/MultiplayerMod
        dotnet build -c Release -r win-x64 --self-contained false
    
    - name: Debug - List build outputs
      run: |
        echo "=== EasyLauncher build output ==="
        dir EasyLauncher\bin\Release\net9.0-windows\win-x64\
        echo "=== CastleStoryLauncher build output ==="
        dir Components\CastleStoryLauncher\bin\Release\net9.0-windows\
        echo "=== LANServer build output ==="
        dir Components\LANServer\bin\Release\net9.0-windows\
        echo "=== LANClient build output ==="
        dir Components\LANClient\bin\Release\net9.0-windows\
        echo "=== MultiplayerServer build output ==="
        dir Components\MultiplayerServer\bin\Release\net6.0\
        echo "=== MultiplayerMod build output ==="
        dir Components\Mods\MultiplayerMod\bin\Release\net6.0\

    - name: Create Release Package
      run: |
        mkdir Release
        mkdir Release\Components\CastleStoryLauncher
        mkdir Release\Components\LANServer
        mkdir Release\Components\LANClient
        mkdir Release\Components\MultiplayerServer
        mkdir Release\Components\Mods\MultiplayerMod
        mkdir Release\logs
        
        # Copy EasyLauncher files
        if exist EasyLauncher\bin\Release\net9.0-windows\win-x64\EasyLauncher.exe (
            copy EasyLauncher\bin\Release\net9.0-windows\win-x64\EasyLauncher.exe Release\
        )
        if exist EasyLauncher\bin\Release\net9.0-windows\win-x64\EasyLauncher.dll (
            copy EasyLauncher\bin\Release\net9.0-windows\win-x64\EasyLauncher.dll Release\
        )
        if exist EasyLauncher\bin\Release\net9.0-windows\win-x64\*.dll (
            copy EasyLauncher\bin\Release\net9.0-windows\win-x64\*.dll Release\
        )
        
        # Copy CastleStoryLauncher files (WPF app - no .exe, just .dll)
        if exist Components\CastleStoryLauncher\bin\Release\net9.0-windows\CastleStoryLauncher.dll (
            copy Components\CastleStoryLauncher\bin\Release\net9.0-windows\CastleStoryLauncher.dll Release\Components\CastleStoryLauncher\
        )
        if exist Components\CastleStoryLauncher\bin\Release\net9.0-windows\*.dll (
            copy Components\CastleStoryLauncher\bin\Release\net9.0-windows\*.dll Release\Components\CastleStoryLauncher\
        )
        
        # Copy LANServer files
        if exist Components\LANServer\bin\Release\net9.0-windows\LANServer.exe (
            copy Components\LANServer\bin\Release\net9.0-windows\LANServer.exe Release\Components\LANServer\
        )
        if exist Components\LANServer\bin\Release\net9.0-windows\LANServer.dll (
            copy Components\LANServer\bin\Release\net9.0-windows\LANServer.dll Release\Components\LANServer\
        )
        if exist Components\LANServer\bin\Release\net9.0-windows\*.dll (
            copy Components\LANServer\bin\Release\net9.0-windows\*.dll Release\Components\LANServer\
        )
        
        # Copy LANClient files
        if exist Components\LANClient\bin\Release\net9.0-windows\LANClient.exe (
            copy Components\LANClient\bin\Release\net9.0-windows\LANClient.exe Release\Components\LANClient\
        )
        if exist Components\LANClient\bin\Release\net9.0-windows\LANClient.dll (
            copy Components\LANClient\bin\Release\net9.0-windows\LANClient.dll Release\Components\LANClient\
        )
        if exist Components\LANClient\bin\Release\net9.0-windows\*.dll (
            copy Components\LANClient\bin\Release\net9.0-windows\*.dll Release\Components\LANClient\
        )
        
        # Copy MultiplayerServer files
        if exist Components\MultiplayerServer\bin\Release\net6.0\MultiplayerServer.exe (
            copy Components\MultiplayerServer\bin\Release\net6.0\MultiplayerServer.exe Release\Components\MultiplayerServer\
        )
        if exist Components\MultiplayerServer\bin\Release\net6.0\MultiplayerServer.dll (
            copy Components\MultiplayerServer\bin\Release\net6.0\MultiplayerServer.dll Release\Components\MultiplayerServer\
        )
        if exist Components\MultiplayerServer\bin\Release\net6.0\*.dll (
            copy Components\MultiplayerServer\bin\Release\net6.0\*.dll Release\Components\MultiplayerServer\
        )
        
        # Copy MultiplayerMod files
        if exist Components\Mods\MultiplayerMod\bin\Release\net6.0\MultiplayerMod.dll (
            copy Components\Mods\MultiplayerMod\bin\Release\net6.0\MultiplayerMod.dll Release\Components\Mods\MultiplayerMod\
        )
        if exist Components\Mods\MultiplayerMod\mod.json (
            copy Components\Mods\MultiplayerMod\mod.json Release\Components\Mods\MultiplayerMod\
        )
        
        # Copy additional files
        copy version.txt Release\
        copy README.md Release\
        copy CreateRelease.bat Release\
    
    - name: Create ZIP Archive
      run: |
        powershell Compress-Archive -Path Release\* -DestinationPath CastleStoryModdingTool.zip
    
    - name: Upload Release
      uses: actions/upload-artifact@v4
      with:
        name: CastleStoryModdingTool
        path: CastleStoryModdingTool.zip
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: CastleStoryModdingTool.zip
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
